export const authActionTypes = {
    LOGIN_INIT: "@@PESTOMEET__LOGIN_INIT",
    LOGIN_SUCCESS: "@@PESTOMEET__LOGIN_SUCCESS",
    LOGIN_FAIL: "@@PESTOMEET__LOGIN_FAIL",
    LOGOUT_INIT: "@@PESTOMEET__LOGOUT_INIT",
    FRGTPASS_EMAILINIT: "@@PESTOMEET__FRGTPASS_EMAILINIT",
    FRGTPASS_EMAILSUCCESS: "@@PESTOMEET__FRGTPASS_EMAILSUCCESS",
    FRGTPASS_EMAILFAIL: "@@PESTOMEET__FRGTPASS_EMAILFAIL",
    REGISTER_INIT: "@@PESTOMEET__REGISTER_INIT",
    REGISTER_SUCCESS: "@@PESTOMEET__REGISTER_SUCCESS",
    REGISTER_FAIL: "@@PESTOMEET__REGISTER_FAIL",
    LOGOUT: "@@PESTOMEET__LOGOUT",
};
