name: Deploy Backend to Heroku

on:
  push:
    tags:
      - "v*"

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/dist
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "d32c781d-2fba-438e-98f6-99c7dd4fc601"
          heroku_app_name: "pestomeet" #Must be unique in Heroku
          heroku_email: "ninja4epsilon@gmail.com"
          appdir: "backend"
      - run: npm install
      - run: tsc
      - run: npm start
  job2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "72bd2b2e-e4fd-46aa-bddc-55ed02b460b5"
          heroku_app_name: "pestomeet-frontend" #Must be unique in Heroku
          heroku_email: "apurva.w17@gmail.com"
          appdir: "frontend"
      - run: npm install
      - run: npm run start
